# Generated by Django 5.0.7 on 2024-07-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gg_guess_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='countries_guessed',
            field=models.ManyToManyField(blank=True, to='gg_guess_app.country'),
        ),
    ]
